### ISSUE TITLE
Move the front-end to React.js

### ISSUE THREAD

**Issue by akhil-sharma** [akhil-sharma/collaborative_white_board#7]

**Comment by vikashjoshi187** [comment]
Hy Is this issue open i want to contribute.
and please also let me know in which technology you want TS or JS

**Comment by akhil-sharma** [comment]
Hey!
You can work on this issue.
----
1. Typescript
2. Tools like vite preferred over create-react-app
3. Frameworks like Nextjs unnecessary here.

**Comment by vikashjoshi187** [comment]
Sorry I assumed that that you want in JS.
i never Worked  on TS. If  there is any other work that requires JS I will be happy to help you in that.

**Comment by akhil-sharma** [comment]
No problem.

Le lun. 16 sept. 2024, 07:49, vikas joshi ***@***.***> a
écrit :
